openapi: "3.0.3"
info:
  title: Comics Paper Server
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /users/signup:
    post:
      description: "Sign up for new account"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                  format: email
                nickname:
                  type: string
              required:
                - username
                - password
                - email
                - nickname

      responses:
        "200":
          description: Successfully registration
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/UserResponseInterface"

        "400":
          description: Missing username, password or email
          # content:
          # application/json:
  /users/signin:
    post:
      description: "Sign in as a user"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/UserRequestSignInInterface"
      responses:
        "200":
          description: "Successfully sign in"
components:
  schemas:
    UserResponseInterface:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        username:
          type: string
        email:
          type: string
          format: email
        nickname:
          type: string

    UserRequestSignInInterface:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
          format: "password"
      required:
        - username
        - password
